version: "3"

services:
  app:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fk
      DATABASE_URL: jdbc:postgresql://fkdb:5432/fk
      PORT: 9908
    build: .
    image: bonganimbigi/my-springboot-helloworld:latest
    container_name: hello-world
    ports:
      - "9908:9908"
    depends_on:
      - fk-db
  fk-db:
    image: postgres
    container_name: fkdb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fk